[END]
pneumonic = "end"
category = "marker"
description = "marker for the end of execution"
value = 0

[ADD]
pneumonic = "add"
category = "arithmetic"
description = "add the first two values on the stack"
value = 1000

[SUB]
pneumonic = "subtract"
category = "arithmetic"
description = "subtract the second value on the stack from the first"
value = 1010

[EQU]
pneumonic = "equal"
category = "comparison"
description = "compare the first two values on the stack for equality"
value = 2000

[CMP]
pneumonic = "compare"
category = "comparison"
description = "compare first two values on the stack and set -1 if the first is greater, etc"
value = 2010

[NOT]
pneumonic = "not"
category = "logical"
description = "logically invert the value at the top of the stack"
value = 3000

[JNZ]
pneumonic = "jump non-zero"
category = "jump"
description = "jump to the address at the top of the stack if the second value on the stack is non-zero"
value = 4000

[JNE]
pneumonic = "jump not-equal"
category = "jump"
description = "jump if the next two values on the stack are equal"
value = 4010

[JGT]
pneumonic = "jump greater-than"
category = "jump"
description = "jump if the second value on the stack is greater than the third value"
value = 4020

[JLT]
pneumonic = "jump less-than"
category = "jump"
description = "jump if the value at the top of the stack is less than the next value"
value = 4030

[REA]
pneumonic = "read"
category = "memory"
description = "read from the memory location pointed at by the value at the top of the stack and push its value"
value = 5000

[WRI]
pneumonic = "write"
category = "memory"
description = "write the second value on the stack to the memory location pointed at by the value at the top of the stack"
value = 5010

[REN]
pneumonic = "read to length"
category = "memory"
description = "read from the memory location pointed to by the value at the top of the stack, and read a number of words given by the second value on the stack"
value = 5020

[WEN]
pneumonic = "write to length"
category = "memory"
description = "write a number of values corresponding to the second value on the stack (they will be popped) to the range of memory starting at the location pointed to by the value at the top of the stack"
value = 5030

[PSH]
pneumonic = "push"
category = "stack"
description = "push a value on to the top of the stack"
value = 6000
